### ISSUE TITLE
Create pytest function setup/tear-down that adds and removes symlinks

### ISSUE THREAD

**Issue by MattPitlyk** [GlobalHack/cemaritan#71]

**Comment by kylesykes** [comment]
1. add symlinks
2. calls the top levels functions against either a local database or the AWS postgres (my choice)
3. removes symlinks

that would be awesome
I can make the aws `event` objects
but a way to say: here’s my event object, pass it to this function, and make sure this gets returned

Note to self:
- Mock postgres call (maybe just mock the return from the db_queries functions for ease?)
- If I setup an integration test with live postgres, setup local script for Matt to run and set env variables for connecting to postgres
